//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverloadableContract.Client.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/AddWithTwoOperans", ReplyAction="http://tempuri.org/ICalculator/AddWithTwoOperansResponse")]
        double AddWithTwoOperans(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/AddWithTwoOperans", ReplyAction="http://tempuri.org/ICalculator/AddWithTwoOperansResponse")]
        System.Threading.Tasks.Task<double> AddWithTwoOperansAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/AddWithThreeOperands", ReplyAction="http://tempuri.org/ICalculator/AddWithThreeOperandsResponse")]
        double AddWithThreeOperands(double x, double y, double z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/AddWithThreeOperands", ReplyAction="http://tempuri.org/ICalculator/AddWithThreeOperandsResponse")]
        System.Threading.Tasks.Task<double> AddWithThreeOperandsAsync(double x, double y, double z);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : OverloadableContract.Client.CalculatorService.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<OverloadableContract.Client.CalculatorService.ICalculator>, OverloadableContract.Client.CalculatorService.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AddWithTwoOperans(double x, double y) {
            return base.Channel.AddWithTwoOperans(x, y);
        }
        
        public System.Threading.Tasks.Task<double> AddWithTwoOperansAsync(double x, double y) {
            return base.Channel.AddWithTwoOperansAsync(x, y);
        }
        
        public double AddWithThreeOperands(double x, double y, double z) {
            return base.Channel.AddWithThreeOperands(x, y, z);
        }
        
        public System.Threading.Tasks.Task<double> AddWithThreeOperandsAsync(double x, double y, double z) {
            return base.Channel.AddWithThreeOperandsAsync(x, y, z);
        }
    }
}
